#+hugo_base_dir: ../
#+author: Vladimir Bajčeta

* IBM Power :@power:
** Installing Void Linux on IBM Power 740                         :ibm:linux:
:PROPERTIES:
:EXPORT_FILE_NAME: void-linux-ibm-power-740
:EXPORT_DATE: 2022-03-31
:EXPORT_HUGO_MENU: :menu "ibm"
:END:


*** Going for Void Linux

Recently I switched from Ubuntu to [[https://voidlinux-ppc.org/][Void Linux]] on all my boxes. Fortunately Void has great support for PPC.
I even have it installed on a Powerbook G3.

For running Linux on PPC you need to know if your CPU support little endian or big endian. PowerPC started as BE and only with Power8 did it fully support LE mode.
For a Power7 we need Void Linux ppc64 that is a BE version.

I prefer minimal installs and adding on packages that I need later so I went for [[https://repo.voidlinux-ppc.org/live/20210825/void-live-ppc64-20210825.iso.][void-live-ppc64-20210825.iso]].

*** Making a bootable USB on Linux
1. insert the drive
2. check the drive id with =dmesg=, sdb in my case
3. unmount the drive if you have an automount daemon running
4. copy the iso to usb with ~dd~


#+begin_src
umount /dev/sdb
dd if=void-live-ppc64-20210825.iso of=/dev/sdb bs=1m
#+end_src

*** Using HMC

I don't have the RJ45 serial cable so I had to install HMC in order to use a virtual console for the install.
I found that the =HMC_Recovery_V8R870_1_x86.iso= can be installed in a VM and used to manage the server.


Default user for HMC is ~hscroot~ and password is ~abc123~.

I couldn't get the virtual console running in a browser so I had to ssh into the HMC VM and use ~vtmenu~.

*** Installing Void Linux

1. Create a new LPAR and assign the usb controller to it.
2. Don't forget to plug in the USB you created before.
3. Boot into Open Firmware and type:
#+begin_src
devalias ud /pci@f2000000/usb@1b/disk@1
boot ud:,\boot\grub.img
#+end_src
You might have to change the devalias command to fit your setup. Use =ls= and =dev= commands in OF to navigate and find your device.
4. Grub prompt should appear.
Boot takes a lot of time, loading the kernel and initrd can take 10-20 minutes easy. It's much faster after the install.

** IBM Power 740                                                        :ibm:
:PROPERTIES:
:EXPORT_FILE_NAME: ibm-power-740
:EXPORT_DATE: 2022-03-27
:EXPORT_HUGO_MENU: :menu "ibm"
:END:


I saw the server on an auction with just a few minutes to spare. Always liked PPC for some reason, so it peaked my interest. Ad was sparse with info, 2 cpus, 384GB, no disks. No clue on which CPUs, was it really 384GB ram... Anyway I went for it.

Turns out it was a top of the line box.

Specs:
 - 2 x 8 core Power7 @3.55GHz
 - 384GB ram
 - 4 x 146GB  15k SAS

All CPUs and ram activated and has a PowerVM license.

Power consumption is not so good, it idles at around 360w-400w. I'll try pulling out some drives and PCIe cards that sit unused. It might take the consumption down by 20-40w.
In comparison a Dell R620 can idle at around 100w.

One of the selling points for IBM Power servers is the massive IO that they support. Power 740 is a mid level server from the series and it can support up to 4 IBM 5802 enclosures for a total of 4x 18 SAS drives and 4x 10 PCIe slots. I am not aware of any x86 system offering such expansion.

*** IBM Power terminology

PowerVM - Hypervisor, like KVM or VMware on x86.

LPAR - Logical partition, what we would today call a VM.

Hardware Management Console - IBM appliance or VM that is used to manage virtualization of PowerVM

VIOS - Virtual IO Server, AIX instance that shares physical resources as virtual ones to other LPARs.

IBM Power7 servers always run a hypervisor, even when all resources are dedicated to one LPAR.

*** Uses for this server?

Getting AIX requires a service agreement with IBM, so that is out the question.

It might serve as a build server for Void Linux PPC BE packages, since the maintaner can't afford the time to continue. Not sure if I can, but I like the thought.
